export const meta = { name:'coge-si-name-verify', description:'Verify Staten Island witness names', phases:[{title:'Verify'}] }
const witnesses = [{"name": "Kauran Santas", "affiliation": "Resident; infrastructure and energy-transition professional, member of the Riverside Conservancy", "role_type": "Resident", "quote": "Sunlight is the cheapest auditor."}, {"name": "Amanda Page-Hoongrajok", "affiliation": "Assistant Professor of Economics, Fashion Institute of Technology (FIT)", "role_type": "Academic", "quote": "You could have painful spending cuts happening while money is just sitting in a reserve and you're not able to use it."}, {"name": "Martin Bernstein", "affiliation": "Economist (testifying on revenue stabilization fund design)", "role_type": "Academic", "quote": "Tying the government's hands can also have real economic risks, even though these rules are certainly well-intentioned."}, {"name": "Melissa Caballero", "affiliation": "Resident; Staten Island non-driver", "role_type": "Resident", "quote": "Those bus lanes are always occupied by cars parked there, and they never seem to move."}, {"name": "Eric Richardson", "affiliation": "Retired NYC fleet management official (23 years at Department of Citywide Administrative Services / NYC Fleet, retired July 2024)", "role_type": "Government body", "quote": "This proposal is not about correcting a failure. It is about preserving success and giving this essential function the permanence it has grown into."}];
const SCHEMA={type:'object',properties:{original_name:{type:'string'},corrected_name:{type:'string'},name_verified:{type:'boolean'},name_confidence:{type:'string',enum:['high','medium','low']},affiliation_corrected:{type:'string'},verify_source:{type:'string'},notes:{type:'string'}},required:['original_name','corrected_name','name_verified','name_confidence']}
phase('Verify')
const results=await parallel(witnesses.map(w=>()=>agent(`Verify the real identity of a witness at the NYC Commission on Government Efficiency (COGE) Round 1 STATEN ISLAND hearing, June 23 2026. The name was auto-transcribed (Whisper) and may be misspelled.
Transcribed name: "${w.name}"
Affiliation/role (also from transcript): ${w.affiliation}
Role: ${w.role_type}
A line from their testimony: "${w.quote}"
Find this person in public records (search the affiliation/org + role, the quote, LinkedIn, faculty pages, news, rosters). Determine the correct spelling + accurate affiliation.
Rules: if CONFIRMED via a public record -> name_verified=true, corrected_name=correct spelling, confidence=high, give verify_source + corrected affiliation. If a likely-but-unconfirmed match -> name_verified=false, confidence=medium, explain. If an ordinary resident with no public footprint -> keep the name, name_verified=false, confidence low (garbled) or medium (ordinary plausible), say so. Never fabricate.
Return original_name="${w.name}", corrected_name, name_verified, name_confidence, affiliation_corrected, verify_source, notes.`,{label:w.name.slice(0,22),phase:'Verify',schema:SCHEMA})))
const r=results.filter(Boolean)
return { results:r, corrections:r.filter(x=>x.corrected_name&&x.corrected_name.toLowerCase()!==x.original_name.toLowerCase()).map(x=>x.original_name+' -> '+x.corrected_name+' ['+x.name_confidence+']') }
